# 适用于java应用的镜像构建脚本，需要引入maven配置文件和缓存包
- name: "生成Dockerfile文件: Dockerfile-{{app_type}}-{{type_version}}"
  template:
    src: "{{workspace}}/ansible/dockerfiles/Dockerfile-{{app_type}}-{{type_version}}"
    dest: "{{workspace}}/Dockerfile"
    force: yes

- name: "创建构建脚本: run_build.sh"
  blockinfile:
    create: yes
    path: "{{workspace}}/run_build.sh"
    block: |
      set -e
      cd {{workspace}}
      docker run --rm \
        -v {{workspace}}/sourcecode:/src \
        -v {{workspace}}/ansible/files/settings.xml:/usr/share/maven/conf/settings.xml \
        -v {{java['repo_dir']}}:/usr/local/maven/repo \
        {{java['v1.8']['build_image']}} /bin/bash -c 'cd /src/{{build_path}} && {{build_command}}'
      docker build --pull -t {{docker_image}} -f {{workspace}}/Dockerfile . --no-cache
      docker --config {{workspace}}/ansible/files/{{register[project_vars['register']]['config']}}/ push {{docker_image}}
      echo "生成镜像：【{{docker_image}}】"
      docker rmi {{docker_image}}
